@echo off
REM FORGE observer launcher — auto-generated by hooks/mcp-deps-install.js on SessionStart.
REM Edits will be overwritten next session. Update the generator if you want a different shape.
"C:\Users\cuj\OneDrive - Nemlig.com\Skrivebord\node-v24.14.0-win-x64\node.exe" "C:\Users\cuj\forge-plugin\scripts\forge-observer.mjs" %*
